services:
  - type: web
    name: policy-final
    env: python
    branch: main
    region: oregon 
    buildCommand: "pip install --no-cache-dir -r requirements.txt"
    startCommand: "streamlit run app.py"
    pythonVersion: "3.13"  

